# automatically starts via a predev command in apps/ws-server
name: simple-stream

services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
