name: simple-stream

services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:

# db:
#   image: postgres:18
#   restart: unless-stopped
#   shm_size: 128mb
#   environment:
#     POSTGRES_PASSWORD: simplestream
#     # optional but explicit on v18+:
#     PGDATA: /var/lib/postgresql/18/docker
#   volumes:
#     - pg_data:/var/lib/postgresql   # v18+ mount parent (modified, no /data)
#   ports:
#     - "5432:5432"
#   healthcheck:
#     test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB:-postgres}"]
#     interval: 10s
#     timeout: 5s
#     retries: 5
# volumes:
#   pg_data:
